- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - name: Pre tools
      ansible.builtin.import_tasks:
        file: ./tasks/preinstall.yaml
    - name: LocalXpose
      ansible.builtin.import_tasks:
        file: ./tasks/localxpose.yaml
