- hosts: localhost
  # vars:
  #   source_key: "./.ssh/id_rsa"
  #   dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  #   personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - name: Include task list in play
      ansible.builtin.import_tasks:
        file: ./tasks/ssh.yaml
    - name: Include task list in play
      ansible.builtin.import_tasks:
        file: ./tasks/node.yaml
