- name: Install vim
  package:
    name: vim
    state: present

- name: Install curl
  package:
    name: curl
    state: present

- name: Install nettools
  package:
    name: net-tools
    state: present
